### PR TITLE
write score to image capability

### PR DESCRIPTION
**Pull request by illtellyoulater**
Note: saving the score into an image will discard all the Exif metadata the image might contain. 
However, it will keep the PNG chunks, which is where Web-UI is storing generation parameters.

### CODE REVIEW

**Comment by vladmandic** [comment]
as i've explained in <https://github.com/vladmandic/sd-extension-aesthetic-scorer/issues/2#issuecomment-1452495325>, i don't want to overwrite existing exif metadata, even with a warning/disclaimer.

but i did recently implement a generic exif metadata parser in a separate pr: <https://github.com/AUTOMATIC1111/stable-diffusion-webui/compare/master...vladmandic:automatic:safe-metadata>

so if you want to combine that somehow so as much as possible metadata is preserved, then this feature can be added.

**Comment by illtellyoulater** [comment]
Sure, it looks interesting, I'll take a look at it.

However I'd like to understand a bit more about your concern for Exif data given the generative context in which we are and in which this extension takes life.

Like, is there anyone approaching Stable Diffusion with the intent of preserving the real-world original Exif data from a picture, after editing it with the most advanced generative AI technology? Maybe I've never dealt to much with metadata to be able to fully understand its value, even in a generative context? I don't know?

Perhaps it's just about embracing an healthy software design principle of not destroying any data which was not meant to be destroyed... And I would fully comply to that... but... I can't get it off my mind that at the end of the day this will be used to assign scores to freshly diffused, genuinely synthetic AI images... so what metadata could there be to preserve?

**Comment by vladmandic** [comment]
my concern is not about EXIF data from generated images, but using the tool on actual pre-existing non-generative images - which people already tried.

**Comment by illtellyoulater** [comment]
Do you think that allowing it to only write on images already containing webui's `parameters` metadata could be a good compromise between safety and functionality? As a countermeasure to risky usage it would work relatively well, while retaining a good level of functionality, and operating consistently to its context of being a Web-UI extension.

**Comment by vladmandic** [comment]
its a good workaround, but i think its better to implement that generic exif parser and rewrite all known exif info while appending score. ok, give me a bit, i'll do it.

**Comment by vladmandic** [comment]
closing this pr in favor of newly added code that uses new universal exif handler.
see <https://github.com/vladmandic/sd-extension-aesthetic-scorer/commit/f379478c2f5e7df68cfbeaec2a410b2b0023e4d0>

**Comment by illtellyoulater** [comment]
Nice one. 
Perhaps there's some kind of popular sample image loaded with crazy amount of Exif data which is typically used as a testing reference for Exif parsers?

**Comment by vladmandic** [comment]
Testing is welcome :)

**Pull request closed without merging**
